export const COLORS = {
    COLOR_TRANSPARENT: 'transparent',
    COLOR_DEFAULT: '#282B30',
    COLOR_DISABLED:'#BFBFC1',
    COLOR_DANGER:'#D0021B',
    COLOR_SUCCESS:'#25CB55',
    COLOR_GOLD:'#FFBD0A',
    COLOR_WHITE:'#FEFEFE',
};

export const ORDER_COLORS = {
    COLOR_DANGER:'#D0021B',
    COLOR_SUCCESS:'#25CB55',
    COLOR_GOLD:'#FFBD0A',
}

export const LIGHT_COLORS = {
    COLOR_JORDY_BLUE: '#99CAF4',
    COLOR_SEA_PINK: '#EC9AA4',
    COLOR_MADANG: '#A8EABB',
    COLOR_CREAM_BRULEE: '#FFE59D',
    COLOR_PERIWINKLE_GRAY: '#C6C6E8',
    COLOR_JAGGED_ICE: '#B2E2E2',
    COLOR_BLUE_CHALK: '#F8CDFF',
    COLOR_WATER_LEAF: '#A8EBEB',
    COLOR_WAX_FLOWER: '#FFC09D',
};
